### ISSUE TITLE
"Loading failed for the <script> with source “http://localhost:8080/client.js”." and more

### ISSUE THREAD

**Issue by Kampfkarren** [Bluespess/tgstation-remake#48]
When I follow the instructions in the repo, I'm left with this.

![image](https://user-images.githubusercontent.com/3190756/40592900-0c6f9f74-61d9-11e8-869b-1e4a014356c8.png)

![image](https://user-images.githubusercontent.com/3190756/40592904-1a43c620-61d9-11e8-9967-a9fb45b96164.png)

I have zero idea how to fix this.

**Comment by monster860** [comment]
Did you run `gulp` in the `client_src` directory?

**Comment by Kampfkarren** [comment]
I thought I did but apparently not. Fixed it.

**Comment by Kampfkarren** [comment]
I'm having another issue (not making a new one just in case it's a me thing again). The screen is black and shows this in the errors...

    TypeError: class heritage Plane is not an object or null    parallax.js:5
