### ISSUE TITLE
Unable to launch.

### ISSUE THREAD

**Issue by dangranos** [Bluespess/tgstation-remake#6]
Okay, this project is awesome because of what it tries to achieve. But the problem is, code published in this repo is not working. At all.

After a few failed attempts to launch the game, slap a hackfix on a thing, and repeating this a few times, I gave up trying to launch it.
So far I found several errors when trying to use `reagents` branch, though probably master branch is not any different:

- https://github.com/Bluespess/tgstation-remake/blob/717d5ce0dbc672a228ec59fc4493320cb198961f/code/game/objects/structures/window.js#L118 - This line gives an error during initial loading of the map, because when template is `Object.assign()`ed in atom.js of `bluespess`, this function is triggered. But the object is not even initialized and doesn't have an `.a` at all!
- Toolbox tries to spawn screwdriver and bunch of other items by passing their template name, but `Atom` constructor is using a template *object*.
And I have no idea what this is even:
```
TypeError: this.a.base_mover.crosses(...) is not iterable
    at Stack.update_recipes (.../tgstation-remake/code/game/objects/items/stacks/stack.js:149:42)
    at Stack.amount_changed (.../tgstation-remake/code/game/objects/items/stacks/stack.js:63:8)
    at new Stack (.../code/game/objects/items/stacks/stack.js:11:8)
    at new Atom (.../tgstation-remake/node_modules/bluespess/lib/atom/atom.js:147:38)
    at Bluespess.instance_map (.../tgstation-remake/node_modules/bluespess/lib/server.js:367:5)
    at Object.<anonymous> (.../tgstation-remake/index.js:79:9)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
```

**Comment by LordWalnut** [comment]
How exactly are you trying to launch it?

**Comment by dangranos** [comment]
Using the instruction from `readme.md`: 
> Run `node index.js` in the root directory of the repository. To join the server connect to localhost:8080 using a web browser.

As you can guess, the above problems come up when I do `node index.js`. I have tried both the `master` and `reagents` branches.

I would assume that you are asking this because for some reason the game actually runs for you? How do you launch it then?

**Comment by monster860** [comment]
I really need to update the readme, it's out of date.

1. Clone both `http://github.com/bluespess/bluespess.git` and `http://github.com/bluespess/tgstation-remake.git`
2. Open a cmd line window in the bluespess repo
3. Type in `npm link`, folowed by `cd client`, then `npm link` again.
4. Open another cmd line window in the tgstation-remake repo, and type in `npm install` then `npm link bluespess` then `cd client_src` then `npm install` then `npm link bluespess-client` then `gulp`

**Comment by dangranos** [comment]
Thanks! I really wish `npm` didn't stupidly downloaded `bluespess` from, well, NPM. Because someone published it. I guess issue is resolved, once you do update the readme. Thanks!

**Comment by monster860** [comment]
I published it, and got tired of updating it every other day.

**Comment by dangranos** [comment]
Then how about unpublishing it? That would definitely make everyone's life
easier.

пн, 25 дек. 2017 г. в 22:13, monster860 <notifications@github.com>:
