### ISSUE TITLE
Didn't open instead this...

### ISSUE THREAD

**Issue by semihezen** [Bluespess/tgstation-remake#69]
![err](https://user-images.githubusercontent.com/17615271/47952939-82a17b00-df87-11e8-8fc0-8cd8ffd53d06.png)

Gives 
Failed to load resource: the server responded with a status of 404 (Not Found)

Refused to apply style from 'http://localhost:8080/client.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

on the devtools

**Comment by monster860** [comment]
what web browser are you using?

**Comment by semihezen** [comment]
> what web browser are you using?

Chrome

more specifically as an app version
5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

i also tried in Firefox
I am sure i followed the setup steps in order i don't know what went wrong

**Comment by monster860** [comment]
Hey, I have a possible solution.

Could you make sure that `C:\Users\[whatever]\AppData\Roaming\npm` is added to your PATH?
