### ISSUE TITLE
You can put lockers in lockers and I can't escape the shuttle.

### ISSUE THREAD

**Issue by Rommist64** [Bluespess/tgstation-remake#78]
Yes, I haven't really played much SS13, as I don't want to spend money for it, but I'm fairly certain that you can't put a locker in a locker in a locker in a locker. Also I am stuck inside the shuttle for some reason. Not a bug, but I'm just bringing it up.
[Not a gif but a related video I tried to make it a gif help.zip](https://github.com/Bluespess/tgstation-remake/files/2692791/Not.a.gif.but.a.related.video.I.tried.to.make.it.a.gif.help.zip)

**Comment by monster860** [comment]
the lockers aren't inside each other, they're simply occupying the same tile.

**Comment by monster860** [comment]
also the shuttle is inescapable because the power died.

**Comment by sustox** [comment]
ss13 is a free game

**Comment by Kinrany** [comment]
> also the shuttle is inescapable because the power died. use a crowbar.

Are there enough spare crowbars on the shuttle? Seems important that people can actually try the remake.

**Comment by ike709** [comment]
You can always smash the shuttle window and the adjacent station window without depressurizing anything. SS13 isn't that difficult, guys.

**Comment by Kinrany** [comment]
Smashing windows works too, as long as there's something with more damage than your slippers.

**Comment by monster860** [comment]
Fun fact: I haven't implemented burning your hand off with lights yet. Just take a light fixture and start bashing window with it
